### ISSUE TITLE
wrong instructuons for morse update?

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_systems#10]
I was uopdating morse using the instructions but morse kept crashing because of the new battery_state implementation.

To update it correctly, I ignored point 3. of the instructions: `cd build`. Now it works and I can start morse normally

Is this an error or was I doing something wrong?

**Comment by cdondrup** [comment]
That shouldn't have worked. Because 

```
cmake -DCMAKE_INSTALL_PREFIX=${workspace} -DPYMORSE_SUPPORT=ON -DPYTHON_EXECUTABLE=${workspace}/bin/python3.3 -DBUILD_ROS_SUPPORT=ON ..
```

tells cmake to look for the CMakeLists in the parent directory. Maybe you forgot the `..` at the end?!

**Comment by bfalacerda** [comment]
ah, yes
i'll close this then :)
