### ISSUE TITLE
Reconcile Wiki vs README

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_systems#11]
There are currently two sources of install/how to information:

https://github.com/strands-project/strands_systems/wiki/HowTo

and 

https://github.com/strands-project/strands_systems/blob/master/README.md

I'm in favour of moving all this to the strands_systems wiki for easier editing and linking to subsections. It's a relatively simple fix if everyone agrees,

**Comment by marc-hanheide** [comment]
done it!
