### ISSUE TITLE
error in catkin_make for the strands_system files

### ISSUE THREAD

**Issue by OMARI1988** [strands-project/strands_systems#13]
Hi,

I am getting this error when I use the catkin_make command in the strands_catkin_ws

/usr/bin/ld: warning: libopencv_core.so.2.3, needed by /opt/MIRA/lib/libMIRABase.so, may conflict with libopencv_core.so.2.4
[ 82%] Built target scitos_node
make: **\* [all] Error 2
Invoking "make" failed

Can someone please advice ?

Muhannad
Univ of Leeds

**Comment by cdondrup** [comment]
That's just a warning which does not make the build process crash.
The error must be before that... Since catkin is highly multi threading the error is not always the last output of the make process.
Have a look at the whole output and search for the error message.

**Comment by OMARI1988** [comment]
[ 82%] Building CXX object strands_perception_people/strands_visual_odometry/CMakeFiles/visual_odometry.dir/3rd_party/fovis/libfovis/internal_utils.cpp.o
In file included from /opt/strands_final/strands_catkin_ws2/src/strands_perception_people/strands_visual_odometry/3rd_party/fovis/libfovis/internal_utils.hpp:8:0,
                 from /opt/strands_final/strands_catkin_ws2/src/strands_perception_people/strands_visual_odometry/3rd_party/fovis/libfovis/internal_utils.cpp:4:
/usr/lib/gcc/i686-linux-gnu/4.6/include/emmintrin.h:32:3: error: #error "SSE2 instruction set not enabled"
make[2]: **\* [strands_perception_people/strands_visual_odometry/CMakeFiles/visual_odometry.dir/3rd_party/fovis/libfovis/internal_utils.cpp.o] Error 1
make[1]: **\* [strands_perception_people/strands_visual_odometry/CMakeFiles/visual_odometry.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 82%] Building CXX object strands_perception_people/strands_pedestrian_tracking/CMakeFiles/pedestrian_tracking.dir/src/Visualization.cpp.o
Linking CXX executable /opt/strands_final/strands_catkin_ws2/devel/lib/strands_pedestrian_tracking/pedestrian_tracking
[ 82%] Built target pedestrian_tracking
make: **\* [all] Error 2
Invoking "make" failed

**Comment by cdondrup** [comment]
I see. This tells me that you want to install everything on a 32bit Ubuntu, right? This is generally not a very good idea since all of us should use a 64bit system to keep everything consistent and also some of the standard ROS nodes are not optimized to be run under 32bit. If you want to make it run any ways, please follow the troubleshooting instructions here: https://github.com/strands-project/strands_perception_people/tree/master/strands_visual_odometry#troubleshooting

**Comment by hawesie** [comment]
It was agreed that we would all run 64bit Ubuntu 12.04: https://github.com/strands-project/strands_management/wiki/Best-practices

**Comment by OMARI1988** [comment]
Thanks, we will install the 64 bit version now.

Best regards,
Muhannad Al-Omari
PhD candidate in Cognitive Robotics
University of Leeds
447459030874

**Comment by cdondrup** [comment]
Ok, I will close this then. Just open a new issue if you run into problems again.
