### ISSUE TITLE
MIRA installation not working

### ISSUE THREAD

**Issue by OMARI1988** [strands-project/strands_systems#15]
Hi,

I installed the 64-bit ubuntu on the robot, now am trying to do the MIRA installation in /opt/MIRA I am following the exact procedure for the 64-bit system but it stops working when it reaches (INFO: Add installation repository) this is what I get on the screen and then it just stops there !

INFO: Create install directory...
INFO: Downloading MIRAEnvironment...
INFO: Downloading MIRA external...
INFO: Downloading MIRABase...
INFO: Downloading MIRAPackage...
INFO: Unzip MIRAenvironment...
INFO: Unzip MIRA external...
INFO: Unzip MIRABase...
INFO: Unzip MIRAPackage...
INFO: Fixing directory names in MIRA base system.
INFO: Clear repositories.
INFO: Add installation repository
INFO: Reindex installation repository

Muhannad / Leeds

**Comment by hawesie** [comment]
Anyone got any insight into this? @cdondrup @cburbridge?

**Comment by cdondrup** [comment]
As far as I remember we did not encounter any problems with that. Maybe we should move this issue to the scitos_robot repo and include the MetraLabs guys in the discussion.

**Comment by OMARI1988** [comment]
Should I repost it there ?
- Muhannad

**Comment by hawesie** [comment]
Yes, that's probably the best place. We can then copy in the MetraLabs guys. Alternatively you could see if there is a support email for Mira.

**Comment by krishnadubba** [comment]
Does anyone know how to get access to https://www.mira-project.org/svn/MIRA/trunk. This is the only option left for us which we have not tried. We completely cleaned the system but no use. I should be asking this question in MIRA QA forum, but MIRA is testing our patience, I can't even post a question in their QA forum, it comes up blank!

**Comment by OMARI1988** [comment]
Its fixed now.
