### ISSUE TITLE
Build errors on Desktop

### ISSUE THREAD

**Issue by ghost** [strands-project/strands_systems#22]
I wasn't really sure where to put this, but as the guide is in this repo, I will just post it here. 

We tried checking out the full desktop version of the strands system as described in the README, initially we got the following error:

```
-- ==> add_subdirectory(catkinized_navigation/nav_core)
CMake Error at /opt/strands/strands_catkin_ws/devel/share/costmap_2d/cmake/costmap_2dConfig.cmake:95 (message):
  Project 'costmap_2d' specifies '/usr/include/openni' as an include dir,
  which is not found.  It does neither exist as an absolute directory nor in
  '/opt/strands/strands_catkin_ws/src/catkinized_navigation/costmap_2d//usr/include/openni'.
  Ask the maintainer 'contradict <contradict@gmail.com>' to fix it.
Call Stack (most recent call first):
  /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:72 (find_package)
  catkinized_navigation/nav_core/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
Invoking "cmake" failed
```

This was fixed with sudo apt-get install openni-dev, however the next problem was this:

```
-- openni_saver: 0 messages, 1 services
CMake Error at data_compression/openni_saver/CMakeLists.txt:81 (add_dependencies):
  add_dependencies called with incorrect number of arguments
```

finished by this:

```
-- Configuring incomplete, errors occurred!
Invoking "cmake" failed
```

Any ideas? We need this robot to run the web publisher.

**Comment by hawesie** [comment]
Looks like a version mismatch for row, catkin or something else to me. But that's just a guess.

The good news it that you don't need to build everything for this. Just build the package you're targeting with the `--pkg` argument to `catkin_make`, e.g. `catkin_make --pkg strands_webtools`. This should hopefully avoid the openni stuff. If this doesn't work, build with `-j1` and post the full output as a gist.

**Comment by nilsbore** [comment]
So for the openni_saver, Rares' has had the same problem. Commenting line 81 in `data_compression/openni_saver/CMakeLists.txt`: `add_dependencies(openni_image_saver ${catkin_EXPORTED_TARGETS})` should probably do it. The strange thing is that this was added to fix an earlier build problem since openni_image_saver needed to have the server header files exported from the package. This was supposed to be the way to do this and seems to have worked in most cases.

**Comment by marc-hanheide** [comment]
has been fixed now
