### ISSUE TITLE
Could not find MIRA package file 'SCITOS'

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_systems#3]
ad 8.) catkin_make on the robot gives the error "Could not find MIRA package file 'SCITOS'". 
Do I have to set $MIRA_PATH / $LD_LIBRARY_PATH to any specific location or download any other packages? 
Already tried  a few combinations but not very successful so far.

**Comment by cburbridge** [comment]
Is this for a fresh install, or an update of a previous one?

**Comment by ToMadoRe** [comment]
fresh install

**Comment by cburbridge** [comment]
is there any other output?

**Comment by cburbridge** [comment]
is this as installed from Metralabs or is it a new installation?

**Comment by ToMadoRe** [comment]
give me 5 mins - just have to start the robot again... 
MIRA was installed from Metralabs but the rest was carried out as stated in the tutorial

**Comment by cburbridge** [comment]
Are you using a new user account on the robot, or the demo account? If a new account, make sure that you have the same variables in ~/.bashrc as in ~demo/.bashrc

**Comment by ToMadoRe** [comment]
CMakeError at /opt/MIRA/make/Package.cmake:458 (message):
 Cannot find MIRA package file 'SCITOS'.
Call Stack (most recent call first):
 scitos_drivers/scitos_mira/CMakeLists.txt:12 (MIRA_REQUIRE_PACKAGE)

**Comment by ToMadoRe** [comment]
i am using a new user account  - so that might be the issue... i will have a look

**Comment by ToMadoRe** [comment]
Alright thanks, that fixed this problem. I still have some problems though with missing configuration files. Do you have a simple solution for this as well?

CMake Error at /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:72 (find_package):
  Could not find a configuration file for package robot_pose_publisher.

  Set robot_pose_publisher_DIR to the directory containing a CMake
  configuration file for robot_pose_publisher.  The file will have one of the
  following names:

```
robot_pose_publisherConfig.cmake
robot_pose_publisher-config.cmake
```

Call Stack (most recent call first):
  strands_webtools/CMakeLists.txt:7 (find_package)

CMake Error at /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:72 (find_package):
  Could not find a configuration file for package rosbridge_library.

  Set rosbridge_library_DIR to the directory containing a CMake configuration
  file for rosbridge_library.  The file will have one of the following names:

```
rosbridge_libraryConfig.cmake
rosbridge_library-config.cmake
```

Call Stack (most recent call first):
  strands_webtools/CMakeLists.txt:7 (find_package)

CMake Error at /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:72 (find_package):
  Could not find a configuration file for package rosbridge_server.

  Set rosbridge_server_DIR to the directory containing a CMake configuration
  file for rosbridge_server.  The file will have one of the following names:

```
rosbridge_serverConfig.cmake
rosbridge_server-config.cmake
```

Call Stack (most recent call first):
  strands_webtools/CMakeLists.txt:7 (find_package)

**Comment by marc-hanheide** [comment]
That's most likely missing packages that you should have installed via deb packages. Did you do `sudo apt-get install ros-groovy-rosbridge-suite ros-groovy-robot-pose-publisher ros-groovy-tf2-web-republisher ros-groovy-mjpeg-server` as described in https://github.com/strands-project/strands_systems

**Comment by ToMadoRe** [comment]
Great. I actually thought I installed this packages already but anyway, it works now :) Thank you very much!
