### ISSUE TITLE
catkin problem

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_systems#30]
I have the following issue with the current ROS Groovy configuration:

As soon as I source /opt/strands/strands_catkin_ws/devel/setup.bash, the catkin_make command is not found any more. 

I can do source /opt/ros/groovy/setup.bash and it works, but just until I do another source /opt/strands/strands_catkin_ws/devel/setup.bash.

Also, I get the following CMake Error when invoking catkin_make:

```
CMake Warning at /opt/ros/groovy/share/catkin/cmake/test/download_test_data.cmake:9 (message):
  download_test_data() is deprecated, please use catkin_download_test_data()
  instead.

  Use the following signature:

  catkin_download_test_data(download_data_test_willow-full-0.05.pgm
  http://pr.willowgarage.com/data/amcl/willow-full-0.05.pgm FILENAME
  test/willow-full-0.05.pgm MD5 b61694296e08965096c5e78611fd9765)
Call Stack (most recent call first):
  catkinized_navigation/amcl/CMakeLists.txt:78 (download_test_data)


-- +++ processing catkin package: 'ap_msgs'
-- ==> add_subdirectory(autonomous_patrolling/ap_msgs)
CMake Error at /opt/ros/groovy/share/genmsg/cmake/genmsg-extras.cmake:252 (message):
  Could not find 'share/std_msgs/cmake/std_msgs-msg-paths.cmake' (searched in
  '/opt/strands/strands_catkin_ws/devel').
Call Stack (most recent call first):
  autonomous_patrolling/ap_msgs/CMakeLists.txt:46 (generate_messages)


-- Configuring incomplete, errors occurred!
Invoking "cmake" failed
```

**Comment by cdondrup** [comment]
Can you check your `ROS_PACKAGE_PATH` after sourcing: `/opt/strands/strands_catkin_ws/devel/setup.bash`? Does it still include `/opt/ros/groovy/share:/opt/ros/groovy/stacks`?

**Comment by ToMadoRe** [comment]
It does

**Comment by cdondrup** [comment]
Strange... Have you tried the hard counter to every catkin problem? Deleting devel and build directory and building everything again? ;)

**Comment by ToMadoRe** [comment]
I tried a few things...
Removed the whole strands_catkin_ws and compiled everything again. Before that, I deleted the ~/.ros folder, unset ROS_PACKAGE_PATH and CMAKE_PREFIX PATH, did a rosdep init and rosdep update again,...

**Comment by ToMadoRe** [comment]
with "compile" I mean the error message that I posted

**Comment by ToMadoRe** [comment]
Okay, I re-installed groovy and now it seems to work.
