### ISSUE TITLE
strands_systems not in install files

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_systems#40]
The strandds_systems repo is not in any of the rosinstall yaml files. Should we add it to strands-base or strands-extras?

**Comment by hawesie** [comment]
But it's the repo that _contains_ the yaml files...

**Comment by bfalacerda** [comment]
yes, but it also contains the launch files for bob and linda, so we want to have it in the system

**Comment by hawesie** [comment]
I'm not sure, as it feels wrong to have this in everyone's install. Probably we should separate out site specific stuff. @marc-hanheide?

**Comment by marc-hanheide** [comment]
Hmm.... if it goes in it goes in extras. But I'm not 100% sure. I'd say, put it in for now, but we might have to look into this later again.

**Comment by bfalacerda** [comment]
closing old issue that doesnt matter anymore
