### ISSUE TITLE
where is strands_datacentre?

### ISSUE THREAD

**Issue by mzillich** [strands-project/strands_systems#48]
I can not run

roslaunch strands_datacentre datacentre.launch

I only have ros_datacentre

**Comment by hawesie** [comment]
`roslaunch ros_datacentre datacentre.launch`

where is that instruction?

**Comment by mzillich** [comment]
In strands_uol_sim/README.md
I assumed it was ros_datacentre, just wanted to make sure I am not missing some repo.

**Comment by mzillich** [comment]
@Jailander : there is strands_datacentre in the mht_sim.launch file. Is that correct, or should it be ros_datacenre?

**Comment by Jailander** [comment]
Hi, sorry that is a file from the old version that was never updated, I will fix it immediately

**Comment by Jailander** [comment]
it is ros_datacentre

**Comment by Jailander** [comment]
I just changed strands_datacentre to ros_datacentre in the launch file
