### ISSUE TITLE
strands-deployment

### ISSUE THREAD

**Issue by lucasb-eyer** [strands-project/strands_systems#50]
@marc-hanheide you added that dependency yesterday, but the repo doesn't exist. Note that `wstool update --continue-on-error` doesn't help.

**Comment by marc-hanheide** [comment]
sorry... where exactly is this happening? What did I break?

**Comment by lucasb-eyer** [comment]
It's fixed now. The `strands-project/strands_deployment` repo wasn't visible to me (and others.)
