### ISSUE TITLE
sourcing multiple workspaces

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_systems#82]
I get an error if I source multiple workspaces in .bashrc:

```
[ -f /opt/ros/hydro/setup.bash ] && source /opt/ros/hydro/setup.bash
[ -f /opt/mira-scitos/start.bash ] && source /opt/mira-scitos/start.bash
[ -f /opt/strands/strands_catkin_ws/devel/setup.bash ] && source /opt/strands/strands_catkin_ws/devel/setup.bash
```

In particular, this happens for the package `scitos_mira`, which was installed via apt-get and crashes if I source all the workspaces above.
If I only source  /opt/mira-scitos/start.bash, `scitos_mira` launches okay. 

Can maybe someone else check if this also happens on their system (@cburbridge, @nilsbore, @RaresAmbrus) ?

@marc-hanheide: I think I don't have the permission to assign you for this issue, that's why I just mention you here.

**Comment by cdondrup** [comment]
@ToMadoRe, can you please post the ROS and MIRA environement variables after sourcing each of the files?

```
export | grep -i ros
export | grep -i mira
```

should do the trick.

**Comment by ToMadoRe** [comment]
Sure:

```
$ export | grep -i ros
declare -x CMAKE_PREFIX_PATH="/opt/strands/strands_catkin_ws/devel:/opt/ros/hydro"
declare -x CPATH="/opt/strands/strands_catkin_ws/devel/include:/opt/ros/hydro/include"
declare -x LD_LIBRARY_PATH="/opt/strands/strands_catkin_ws/devel/lib:/opt/ros/hydro/lib:/opt/mira-scitos/lib:/opt/MIRA/lib:/opt/MIRA-commercial/lib"
declare -x PATH="/opt/strands/strands_catkin_ws/devel/bin:/opt/ros/hydro/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/mira-scitos/bin:/opt/MIRA/bin::/opt/MIRA-commercial/bin"
declare -x PKG_CONFIG_PATH="/opt/strands/strands_catkin_ws/devel/lib/pkgconfig:/opt/ros/hydro/lib/pkgconfig"
declare -x PYTHONPATH="/opt/strands/strands_catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/hydro/lib/python2.7/dist-packages"
declare -x ROSLISP_PACKAGE_DIRECTORIES="/opt/strands/strands_catkin_ws/devel/share/common-lisp"
declare -x ROS_DISTRO="hydro"
declare -x ROS_ETC_DIR="/opt/ros/hydro/etc/ros"
declare -x ROS_MASTER_URI="http://localhost:11311"
declare -x ROS_PACKAGE_PATH="/opt/strands/strands_catkin_ws/src:/opt/ros/hydro/share:/opt/ros/hydro/stacks"
declare -x ROS_ROOT="/opt/ros/hydro/share/ros"
declare -x ROS_TEST_RESULTS_DIR="/localhome/opt/strands/strands_catkin_ws/build/test_results"
```

```
$ export | grep -i mira
declare -x LD_LIBRARY_PATH="/opt/strands/strands_catkin_ws/devel/lib:/opt/ros/hydro/lib:/opt/mira-scitos/lib:/opt/MIRA/lib:/opt/MIRA-commercial/lib"
declare -x MIRA_PATH="/opt/MIRA:/opt/MIRA-commercial"
declare -x PATH="/opt/strands/strands_catkin_ws/devel/bin:/opt/ros/hydro/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/mira-scitos/bin:/opt/MIRA/bin::/opt/MIRA-commercial/bin"
```

**Comment by marc-hanheide** [comment]
well... obviously, something still changes the `MIRA_PATH` path in the wrong way. And also still includes the old entries into `LD_PACKAGE_PATH`. That is doomed to fail. Neither `/opt/MIRA` nor `/opt/MIRA-commercial` should be anywhere in your environment. Please try to find where this originate from.

**Comment by ToMadoRe** [comment]
Sorry, I still had an export command in the .bashrc. Didn't know that this package works without the original MIRA installation - great!
As already mentioned in other posts, I still have to launch it twice for it to work (otherwise I get errors for the pan-tilt, CAN driver,..). But this also happened before.
