### ISSUE TITLE
Splitting out camera launching

### ISSUE THREAD

**Issue by lucasb-eyer** [strands-project/strands_systems#88]
I'd propose taking the launching of the two cameras to a separate launchfile.

That's because it regularly, but randomly, happens that a camera just doesn't work. Sometimes you have to plug it out and back in and relaunch the nodes, sometimes you need to `rosnode cleanup` because the openni left a mess last time it's been stopped, etc.

This would avoid restarting _everything_ and allow to restart only the cameras. If you agree, I'd take care of this.

@marc-hanheide @Jailander @cdondrup

**Comment by cdondrup** [comment]
Preaching to the choir... I've been saying this for the last year I think.

**Comment by Jailander** [comment]
Ok, I'll do that. Yes @cdondrup you are always right.

**Comment by lucasb-eyer** [comment]
Thanks! Edit: @cdondrup :microphone:

**Comment by cdondrup** [comment]
@Jailander Don't say that. Never feed the troll! ;)

**Comment by Jailander** [comment]
This is already done see https://github.com/strands-project/strands_systems/blob/hydro-devel/strands_bringup/launch/strands_cameras.launch I'll close
